import { designIcon, salesIcon, marketingIcon, financeIcon, techIcon, engineeringIcon, businessIcon, hrIcon  } from "../assets/icons"

export const categories = [
  {
    name: "design",
    icon: designIcon,
  },
  {
    name: "sales",
    icon: salesIcon,
  },
  {
    name: "marketing",
    icon: marketingIcon,
  },
  {
    name: "finance",
    icon: financeIcon,
  },
  {
    name: "technology",
    icon: techIcon,
  },
  {
    name: "engineering",
    icon: engineeringIcon,
  },
  {
    name: "business",
    icon: businessIcon,
  },
  {
    name: "human resource",
    icon: hrIcon,
  },
];

export const openJobs = [
  {
    companyName: "Revolut",
    companyLogo: "",
    location: "",
    position: "",
    type:"",
    description:"",
    categories: [],
    applied: 0,
    capacity: 10,
  },
  {
    companyName: "",
    companyLogo: "",
    location: "",
    position: "",
    type:"",
    description:"",
    categories: [],
    applied: 0,
    capacity: 10,
  },
  {
    companyName: "",
    companyLogo: "",
    location: "",
    position: "",
    type:"",
    description:"",
    categories: [],
    applied: 0,
    capacity: 10,
  },
  {
    companyName: "",
    companyLogo: "",
    location: "",
    position: "",
    type:"",
    description:"",
    categories: [],
    applied: 0,
    capacity: 10,
  },
  {
    companyName: "",
    companyLogo: "",
    location: "",
    position: "",
    type:"",
    description:"",
    categories: [],
    applied: 0,
    capacity: 10,
  },
  {
    companyName: "",
    companyLogo: "",
    location: "",
    position: "",
    type:"",
    description:"",
    categories: [],
    applied: 0,
    capacity: 10,
  },
  {
    companyName: "",
    companyLogo: "",
    location: "",
    position: "",
    type:"",
    description:"",
    categories: [],
    applied: 0,
    capacity: 10,
  },
  {
    companyName: "",
    companyLogo: "",
    location: "",
    position: "",
    type:"",
    description:"",
    categories: [],
    applied: 0,
    capacity: 10,
  },
]